CREATE DATABASE BANCO_DIGITAL;
USE BANCO_DIGITAL;

CREATE TABLE USUARIO (
USUARIO_ID INT NOT NULL AUTO_INCREMENT,
USUARIO_NOME VARCHAR(45) NOT NULL,
USUARIO_SOBRENOME VARCHAR(50) NOT NULL,
USUARIO_DATA_NASC DATE,
USUARIO_CPF CHAR(11) NOT NULL,
USUARIO_SEXO VARCHAR(1),
USUARIO_EMAIL VARCHAR(150) NOT NULL,
CONSTRAINT PK_USUARIO PRIMARY KEY(USUARIO_ID)
);

CREATE TABLE TELEFONE (
TELEFONE_ID INT NOT NULL AUTO_INCREMENT,
TELEFONE_NUMERO VARCHAR(15) NOT NULL,
USUARIO_ID INT,
CONSTRAINT PK_TELEFONE PRIMARY KEY(TELEFONE_ID),
CONSTRAINT FK_USUARIO FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);

CREATE TABLE ENDERECO (
ENDERECO_ID INT NOT NULL AUTO_INCREMENT,
ENDERECO_RUA VARCHAR(100) NOT NULL,
ENDERECO_NUMERO VARCHAR(6) NOT NULL,
ENDERECO_COMPLEMENTO VARCHAR(255),
ENDERECO_CEP CHAR(8) NOT NULL,
ENDERECO_CIDADE VARCHAR(30) NOT NULL,
ENDERECO_BAIRRO VARCHAR(50) NOT NULL,
ENDERECO_ESTADO CHAR(2) NOT NULL,
USUARIO_ID INT,
CONSTRAINT PK_ENDERECO PRIMARY KEY(ENDERECO_ID),
CONSTRAINT FK_ENDERECOUSUARIO FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);

CREATE TABLE TIPO_DE_CONTA (
TIPO_DE_CONTA_ID INT NOT NULL AUTO_INCREMENT,
TIPO_DE_CONTA_NOME VARCHAR(50) NOT NULL,
CONSTRAINT PK_TIPO_DE_CONTA PRIMARY KEY(TIPO_DE_CONTA_ID)
);

CREATE TABLE TIPO_DE_CARTAO (
TIPO_DE_CARTAO_ID INT NOT NULL AUTO_INCREMENT,
TIPO_DE_CARTAO_NOME VARCHAR(50) NOT NULL,
CONSTRAINT PK_TIPO_DE_CARTAO PRIMARY KEY(TIPO_DE_CARTAO_ID)
);

CREATE TABLE CONTA (
CONTA_ID INT NOT NULL AUTO_INCREMENT,
CONTA_NUM_CONTA INT NOT NULL,
CONTA_AGENCIA INT NOT NULL,
CONTA_DIGITO VARCHAR(1) NOT NULL,
CONTA_SENHA VARCHAR(255) NOT NULL,
CONTA_SENHA_ELETRONICA VARCHAR(8) NOT NULL,
TIPO_DE_CONTA_ID INT,
TIPO_DE_CARTAO_ID INT,
USUARIO_ID INT,
CONSTRAINT PK_CONTA PRIMARY KEY(CONTA_ID),
CONSTRAINT FK_TIPO_DE_CONTA FOREIGN KEY(TIPO_DE_CONTA_ID) REFERENCES TIPO_DE_CONTA(TIPO_DE_CONTA_ID),
CONSTRAINT FK_TIPO_DE_CARTAO FOREIGN KEY(TIPO_DE_CARTAO_ID) REFERENCES TIPO_DE_CARTAO(TIPO_DE_CARTAO_ID)
);

CREATE TABLE SERVICO_BANCO (
SERVICO_BANCO_ID INT NOT NULL AUTO_INCREMENT,
SERVICO_BANCO_NOME VARCHAR(50),
SERVICO_BANCO_VALOR DECIMAL (2,2),
TIPO_DE_CONTA_ID INT,
CONSTRAINT PK_SERVICO_BANCO PRIMARY KEY(SERVICO_BANCO_ID),
CONSTRAINT FK_SERVICO_DA_CONTA FOREIGN KEY(TIPO_DE_CONTA_ID) REFERENCES TIPO_DE_CONTA(TIPO_DE_CONTA_ID)
);

CREATE TABLE SERVICO_USUARIO (
SERVICO_USUARIO_ID INT NOT NULL AUTO_INCREMENT,
SERVICO_USUARIO_VALOR_TOTAL DECIMAL (4,2),
SERVICO_BANCO_ID INT,
USUARIO_ID INT,
CONSTRAINT PK_SERVICO_USUARIO PRIMARY KEY(SERVICO_USUARIO_ID),
CONSTRAINT FK_SERVICO_DO_BANCO FOREIGN KEY(SERVICO_BANCO_ID) REFERENCES SERVICO_BANCO(SERVICO_BANCO_ID),
CONSTRAINT FK_SERVICO_DO_USUARIO FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);

CREATE TABLE APLICATIVO (
APLICATIVO_ID INT NOT NULL AUTO_INCREMENT,
APLICATIVO_SENHA VARCHAR(255) NOT NULL,
CONTA_ID INT,
USUARIO_ID INT,
CONSTRAINT PK_APLICATIVO PRIMARY KEY(APLICATIVO_ID),
CONSTRAINT FK_CONTA_APLICATIVO FOREIGN KEY(CONTA_ID) REFERENCES CONTA(CONTA_ID),
CONSTRAINT FK_USUARIO_APLICATIVO FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);

ALTER TABLE CONTA
ADD CONSTRAINT FK_CONTA_USUARIO FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO(USUARIO_ID);