CREATE DATABASE DH_TUBE;

CREATE TABLE PAIS (
ID_PAIS INT NOT NULL AUTO_INCREMENT, 
NOME VARCHAR (100),
CONSTRAINT PK_PAIS PRIMARY KEY (ID_PAIS)
);

CREATE TABLE AVATAR (
ID_AVATAR INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(45),
URL_IMAGEM VARCHAR(100),
CONSTRAINT PK_AVATAR PRIMARY KEY (ID_AVATAR)
);

CREATE TABLE USUARIO (
ID_USUARIO INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(45),
EMAIL VARCHAR(45),
SENHA VARCHAR(45),
DATA_NASC DATETIME,
CEP VARCHAR(45),
ID_AVATAR INT,
ID_PAIS INT,
CONSTRAINT PK_USUARIO PRIMARY KEY(ID_USUARIO),
CONSTRAINT FK_AVATAR FOREIGN KEY(ID_AVATAR) REFERENCES AVATAR(ID_AVATAR),
CONSTRAINT FK_PAIS FOREIGN KEY(ID_PAIS) REFERENCES PAIS(ID_PAIS)
);

CREATE TABLE PLAYLIST (
ID_PLAYLIST INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(45),
DATA_CRIACAO DATETIME,
PRIVADO SMALLINT,
ID_USUARIO INT,
CONSTRAINT PK_PLAYLIST PRIMARY KEY(ID_PLAYLIST),
CONSTRAINT FK_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE VIDEO (
ID_VIDEO INT NOT NULL AUTO_INCREMENT,
TITULO VARCHAR(100),
DESCRICAO TEXT,
TAMANHO DOUBLE,
NOME_ARQUIVO VARCHAR(100),
DURACAO DOUBLE,
IMAGEM VARCHAR (100),
QTD_REPRODUCAO INT,
QTD_LIKE INT,
QTD_DISLIKE INT,
PRIVADO SMALLINT,
DATA_PUBLICACAO DATETIME,
ID_USUARIO INT,
CONSTRAINT PK_VIDEO PRIMARY KEY(ID_VIDEO),
CONSTRAINT FK_USUARIO_VIDEO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE PLAYLIST_VIDEO (
ID_VIDEO INT,
ID_PLAYLIST INT,
CONSTRAINT FK_VIDEO FOREIGN KEY(ID_VIDEO) REFERENCES VIDEO(ID_VIDEO),
CONSTRAINT FK_PLAYLIST FOREIGN KEY(ID_PLAYLIST) REFERENCES PLAYLIST(ID_PLAYLIST)
);

CREATE TABLE CANAL (
ID_CANAL INT NOT NULL AUTO_INCREMENT,
NOME VARCHAR(45),
DESCRICAO TEXT,
DATA_CRIACAO DATETIME,
ID_USUARIO INT,
CONSTRAINT PK_CANAL PRIMARY KEY(ID_CANAL),
CONSTRAINT FK_CANAL_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);
 